name: Build-and-deploy-win
run-name: ${{ github.actor }} is building a Windows release for SODA

on:
  push:
    branches:
      - fix-win-build-action

jobs:
  deploy-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: tools/anaconda-env/environment-Windows.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list

      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.0"

      - name: Install package.json modules and their dependencies
        run: npm install --ignore-scripts

      - name: Build the python server executable
        run: |
          npm run python-onefile-build

      - name: Test the python server executable
        run: |
          nohup ./pyflaskdist/app.exe 4242 > server_output.txt 2>&1 &
          sleep 30
          cat server_output.txt

          # Check if the server started successfully
          if grep -q "Running on http://127.0.0.1:4242/" server_output.txt; then
            echo "Server started successfully."
          else
            echo "Error: Server failed to start."
            # You can perform additional error handling or cleanup here if needed
            # For example, you may want to exit the workflow with an error code
            exit 1
          fi

          # Clean up the temporary output file
          rm server_output.txt

      - name: Deploy the application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run deploy-win
