name: Build-and-deploy-win
run-name: ${{ github.actor }} is building a Windows release for SODA

on:
  push:
    branches:
      - fix-win-build-action

jobs:
  deploy-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: tools/anaconda-env/environment-Windows.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list

      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.0"

      - name: Install package.json modules and their dependencies
        run: npm install --ignore-scripts

      - name: Build the python server executable
        run: |
          npm run python-onefile-build

      - name: Test the python server executable
        run: |
          Start-process -noNewWindow -FilePath .\pyflaskdist\app.exe -ArgumentList "4242"
          Start-Sleep -Seconds 10
          curl http://127.0.0.1:4242/

      - name: Deploy the application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run deploy-win
